### ISSUE TITLE
Error with flutter_gen when running tests: Missing app_localizations.dart file

### ISSUE THREAD

**Issue by ahmedfyala** [ahmedfyala/ecommerce_elevate#6]
I encountered an issue when running tests in my Flutter project. The error occurs when I run the tests, but it gets resolved temporarily after running `flutter pub get`. Below is the error message I get when running the tests:

C:\srcv\flutter\bin\flutter.bat --no-color test --machine --start-paused test\features\auth\presentation\login\login_view_model_test.dart
Testing started at 8:00 AM ...
lib/core/base/base_view_model.dart:8:8: Error: Error when reading '/C:/Users/wwwah/AppData/Local/Pub/Cache/hosted/pub.dev/flutter_gen-5.8.0/lib/gen_l10n/app_localizations.dart': The system cannot find the path specified.

import 'package:flutter_gen/gen_l10n/app_localizations.dart';
       ^ 
lib/core/base/base_view_model.dart:15:3: Error: Type 'AppLocalizations' not found.
  AppLocalizations? locale;
  ^^^^^^^^^^^^^^^^
lib/core/base/base_view_model.dart:15:3: Error: 'AppLocalizations' isn't a type.
  AppLocalizations? locale;
  ^^^^^^^^^^^^^^^^

Failed to load "L:/ecommerce_elevate/test/features/auth/presentation/login/login_view_model_test.dart": Compilation failed for testPath=L:/ecommerce_elevate/test/features/auth/presentation/login/login_view_model_test.dart

This error seems to be caused by a missing or incorrect path for the 'flutter_gen' package. The issue gets resolved temporarily by running `flutter pub get`, but the error reappears when running the tests again. 

Steps to reproduce:
1. Run the test file: `flutter test test/features/auth/presentation/login/login_view_model_test.dart`
2. See the error related to the missing `app_localizations.dart` file.
3. Run `flutter pub get` and the error goes away.
4. The error reappears when running the tests again without running `flutter pub get`.

![image](https://github.com/user-attachments/assets/e067c57a-ec4f-4a34-879f-e9bac4114dba)

**Comment by john-safwat** [comment]
انت بتعمل provide لل AppLocalization ازاي ؟

**Comment by ahmedfyala** [comment]
مش بعملها حاجه فال test
